version: "2"
services:
  people-info:
    build: libraryadministration-baseservice/
    image: people-info-image
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=library_base_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./sidecar/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./sidecar/config.yaml:/etc/grafana/provisioning/config.yaml
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  prometheus:
  grafana:
  db:

