spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_base_db?reWriteBatchedInserts=true
    username: postgres
    password: postgres
server:
  port: 8080
security:
  enabled: false