spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_auth_db
    username: postgres
    password: postgres
server:
  port: 9090
jwt:
  expirationMinutes: 10
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecret
